<<<<<<< HEAD
language: node_js
node_js:
  - "0.8"
  - "0.10"
  - "0.11"

git:
  depth: 1

matrix:
  fast_finish: true
  allow_failures:
    - node_js: "0.11"

notifications:
  irc: "irc.freenode.org#socket.io"
=======
language: node_js
node_js:
  - "0.8"
  - "0.10"
  - "0.11"

git:
  depth: 1

matrix:
  fast_finish: true
  allow_failures:
    - node_js: "0.11"

notifications:
  irc: "irc.freenode.org#socket.io"
>>>>>>> de25cdd8a29ca2bb2c2df08be00b703b967aaed5
